version: '3.4'
services:
    httpd:
        image: nginx:1.19-alpine
        depends_on:
            - php-fpm
        labels:
            traefik.backend: "httpd"
            traefik.frontend.rule: "Host:gitlab-bot.lvh.me"
        volumes:
            - ./:/var/www/html
            - ./provision/vhost.conf:/etc/nginx/conf.d/default.conf
    php-fpm:
        build:
          context: .
          dockerfile: Dockerfile
          args:
            - WITH_XDEBUG=true
        volumes:
            - ./:/var/www/html
        environment:
            # Use snippet bellow to include xdebug3 env variables
            XDEBUG_MODE: develop,debug
            XDEBUG_CONFIG: "client_host=${MY_IP:-172.17.0.1} discover_client_host=0 client_port=9003"
            XDEBUG_TRIGGER: "default_no_matter"
            XDEBUG_SESSION: xdebug
            PHP_IDE_CONFIG: "serverName=${DEV_SERVER_NAME:-gitlab-bot.lvh.me}"
    traefik:
        image: traefik:1.7
        command: --web --docker
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/etc/traefik/traefik.toml
